#!/bin/bash

set -e

storepass='changeit'
if [ -f /etc/default/cacerts ]; then
    . /etc/default/cacerts
fi

setup_path()
{
    for jvm in java-6-openjdk java-7-openjdk java-6-sun; do
	if [ -x /usr/lib/jvm/$jvm/bin/java ]; then
	    break
	fi
    done
    export JAVA_HOME=/usr/lib/jvm/$jvm
    PATH=$JAVA_HOME/bin:$PATH
}

first_install()
{
    find /etc/ssl/certs -name \*.pem | \
    while read filename; do
	alias=$(basename $filename .pem | tr A-Z a-z | tr -cs a-z0-9 _)
	alias=${alias%*_}
        if [ -n "$FIXOLD" ]; then
            echo "-${alias}"
            echo "-${alias}_pem"
        fi
        echo "+${filename}"
    done | \
    java UpdateCertificates -storepass "$storepass"
    if [ $errors -gt 0 ]; then
	echo >&2 "failed (VM used: $jvm)."
	[ -z "$temp_jvm_cfg" ] || rm -f $temp_jvm_cfg
	exit 1
    fi
    echo "done."
    )
}

case "$1" in
    configure)
        if dpkg --compare-versions "$2" le "20100412"; then
            FIXOLD="true"
            cp -f /etc/ssl/certs/java/cacerts /etc/ssl/certs/java/cacerts.dpkg-old
        fi
        if [ -z "$2" -o -n "$FIXOLD" ]; then
	    setup_path

            # TODO: check if we really need it
	    if ! mountpoint -q /proc; then
		echo >&2 "the keytool command requires a mounted proc fs (/proc)."
		exit 1
	    fi

	    if [ ! -f /etc/$jvm/jvm.cfg ]; then
		# the jre is not yet configured, but jvm.cfg is needed to run it
		temp_jvm_cfg=/etc/$jvm/jvm.cfg
		mkdir -p /etc/$jvm
		printf -- "-server KNOWN\n" > $temp_jvm_cfg
	    fi

	    # on first install, remove certs untrusted by the
	    # user/admininstrator, add locally added certs
	    echo "creating $KEYSTORE..."
	    cp /usr/share/ca-certificates-java/cacerts $KEYSTORE
	    first_install

	    [ -z "$temp_jvm_cfg" ] || rm -f $temp_jvm_cfg
	fi
	chmod 600 /etc/default/cacerts || true
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


